import { headers } from "next/headers";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import StyledComponentsRegistry from "../lib/registry";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout(props) {
	const { children } = props;

	// const headersList = headers();
	// const pathname = headersList.get("x-invoke-path") || "";

	return (
		<html lang="en">
			{/* <body className={inter.className} data-page={pathname}> */}
			<body className={inter.className}>
				<StyledComponentsRegistry>
					<Header />
					<main>{children}</main>
					<Footer />
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
